name: 'GS64 CI'
description: 'Load code and run tests for GS64'
inputs:
  project_name:
    description: 'Name of the project under test'
    required: true
  load_spec:
    description: 'Name of the load spec to use'
    required: false
  run_tests:
    description: 'If missing or false the action will only load the code'
    required: false
    default: "false"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project_name }}
    - ${{ inputs.load_spec }}
    - ${{ inputs.run_tests }}
